apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: serviceexample
  namespace: flux-system
spec:
  releaseName: serviceexample
  chart:
    spec:
      chart: serviceexample
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: serviceexample
        namespace: flux-system
  values:
    image:
      repository: samulispi/service-example
      tag: latest
    nats:
      host: nats
      port: 4222
